export const ErrLastNameAtLeast2Characters = new Error('Last name must be at least 2 characters');
export const ErrFirstNameAtLeast2Characters = new Error('First name must be at least 2 characters');
export const ErrPasswordAtLeast6Chars = new Error('Password must be at least 6 characters')
export const ErrEmailInvalid = new Error('Email is invalid');
export const ErrGenderInvalid = new Error("Gender is invalid")
export const ErrBirthdayInvalid = new Error('Birthday is invalid');
export const ErrRoleInvalid = new Error('Role is invalid')
export const ErrEmailExisted = new Error('Email is already existed')
export const ErrInvlidCredential = new Error('Email or password is invalid');
export const UserIsInactive = new Error('User is inactive');
export const ErrInvalidToken = new Error('Invalid token');
export const ErrStatusInvalid = new Error('Status is invalid');